
package ml.yidreamc.upcpay.net.ruijieservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.math.BigDecimal;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SamServicePortType", targetNamespace = "http://api.spl.ruijie.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SamServicePortType {


    /**
     * 
     * @param params
     * @return
     *     returns cacher.RuijieTb.QueryRepairReportResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryRepairReport", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.QueryRepairReport")
    @ResponseWrapper(localName = "queryRepairReportResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.QueryRepairReportResponse")
    public QueryRepairReportResult queryRepairReport(
            @WebParam(name = "params", targetNamespace = "")
                    QueryRepairReportParam params);

    /**
     * 
     * @param userId
     * @return
     *     returns cacher.RuijieTb.FindOnlineStateResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findOnlineState", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.FindOnlineState")
    @ResponseWrapper(localName = "findOnlineStateResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.FindOnlineStateResponse")
    public FindOnlineStateResult findOnlineState(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId);

    /**
     * 
     * @param userId
     * @return
     *     returns cacher.RuijieTb.ResumeUserResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "resumeUser", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.ResumeUser")
    @ResponseWrapper(localName = "resumeUserResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.ResumeUserResponse")
    public ResumeUserResult resumeUser(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId);

    /**
     * 
     * @param password
     * @return
     *     returns cacher.RuijieTb.EncryptPasswordResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "encryptPassword", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.EncryptPassword")
    @ResponseWrapper(localName = "encryptPasswordResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.EncryptPasswordResponse")
    public EncryptPasswordResult encryptPassword(
            @WebParam(name = "password", targetNamespace = "")
                    String password);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createTxid", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.CreateTxid")
    @ResponseWrapper(localName = "createTxidResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.CreateTxidResponse")
    public String createTxid();

    /**
     * 
     * @param queryLoginFailLogParams
     * @return
     *     returns cacher.RuijieTb.QueryLoginFailLogResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryLoginFailLog", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.QueryLoginFailLog")
    @ResponseWrapper(localName = "queryLoginFailLogResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.QueryLoginFailLogResponse")
    public QueryLoginFailLogResult queryLoginFailLog(
            @WebParam(name = "queryLoginFailLogParams", targetNamespace = "")
                    QueryLoginFailLogParams queryLoginFailLogParams);

    /**
     * 
     * @param queryOnlineDetailParams
     * @return
     *     returns cacher.RuijieTb.QueryOnlineDetailResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryOnlineDetail", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.QueryOnlineDetail")
    @ResponseWrapper(localName = "queryOnlineDetailResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.QueryOnlineDetailResponse")
    public QueryOnlineDetailResult queryOnlineDetail(
            @WebParam(name = "queryOnlineDetailParams", targetNamespace = "")
                    QueryOnlineDetailParams queryOnlineDetailParams);

    /**
     * 
     * @param queryOnlineDetailParams
     * @return
     *     returns cacher.RuijieTb.QueryOnlineDetailResultV2
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryOnlineDetailV2", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.QueryOnlineDetailV2")
    @ResponseWrapper(localName = "queryOnlineDetailResponseV2", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.QueryOnlineDetailResponseV2")
    public QueryOnlineDetailResultV2 queryOnlineDetailV2(
            @WebParam(name = "queryOnlineDetailParams", targetNamespace = "")
                    QueryOnlineDetailParams queryOnlineDetailParams);

    /**
     * 
     * @param userId
     * @return
     *     returns cacher.RuijieTb.FindFlowDescInfoResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findFlowDescInfo", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.FindFlowDescInfo")
    @ResponseWrapper(localName = "findFlowDescInfoResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.FindFlowDescInfoResponse")
    public FindFlowDescInfoResult findFlowDescInfo(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId);

    /**
     * 
     * @param exportTables
     * @param ftpServerIp
     * @param ftpServerPort
     * @param ftpBakPath
     * @param ftpUser
     * @param ftpPass
     * @return
     *     returns cacher.RuijieTb.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveFtpExport", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.SaveFtpExport")
    @ResponseWrapper(localName = "saveFtpExportResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.SaveFtpExportResponse")
    public SamApiBaseResult saveFtpExport(
            @WebParam(name = "ftpServerIp", targetNamespace = "")
                    String ftpServerIp,
            @WebParam(name = "ftpServerPort", targetNamespace = "")
                    Long ftpServerPort,
            @WebParam(name = "ftpBakPath", targetNamespace = "")
                    String ftpBakPath,
            @WebParam(name = "ftpUser", targetNamespace = "")
                    String ftpUser,
            @WebParam(name = "ftpPass", targetNamespace = "")
                    String ftpPass,
            @WebParam(name = "exportTables", targetNamespace = "")
                    List<String> exportTables);

    /**
     * 
     * @return
     *     returns cacher.RuijieTb.FindFtpExportResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findFtpExport", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.FindFtpExport")
    @ResponseWrapper(localName = "findFtpExportResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.FindFtpExportResponse")
    public FindFtpExportResult findFtpExport();

    /**
     * 
     * @param refundType
     * @param fee
     * @param txid
     * @param userId
     * @return
     *     returns cacher.RuijieTb.AccountOperationResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "refund", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.Refund")
    @ResponseWrapper(localName = "refundResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.RefundResponse")
    public AccountOperationResult refund(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "refundType", targetNamespace = "")
                    int refundType,
            @WebParam(name = "fee", targetNamespace = "")
                    BigDecimal fee,
            @WebParam(name = "txid", targetNamespace = "")
                    String txid);

    /**
     * 
     * @param fundType
     * @param fee
     * @param txid
     * @param userId
     * @return
     *     returns cacher.RuijieTb.AccountOperationResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fund", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.Fund")
    @ResponseWrapper(localName = "fundResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.FundResponse")
    public AccountOperationResult fund(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "fundType", targetNamespace = "")
                    int fundType,
            @WebParam(name = "fee", targetNamespace = "")
                    BigDecimal fee,
            @WebParam(name = "txid", targetNamespace = "")
                    String txid);

    /**
     * 
     * @param fundType
     * @param fee
     * @param txid
     * @param tradeInfo
     * @param userId
     * @return
     *     returns cacher.RuijieTb.AccountOperationResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bankFund", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.BankFund")
    @ResponseWrapper(localName = "bankFundResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.BankFundResponse")
    public AccountOperationResult bankFund(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "fundType", targetNamespace = "")
                    int fundType,
            @WebParam(name = "fee", targetNamespace = "")
                    BigDecimal fee,
            @WebParam(name = "txid", targetNamespace = "")
                    String txid,
            @WebParam(name = "tradeInfo", targetNamespace = "")
                    TradeInfo tradeInfo);

    /**
     * 
     * @param fileLicenseDb
     * @return
     *     returns cacher.RuijieTb.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addLicense", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.AddLicense")
    @ResponseWrapper(localName = "addLicenseResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.AddLicenseResponse")
    public SamApiBaseResult addLicense(
            @WebParam(name = "fileLicenseDb", targetNamespace = "")
                    FileLicenseDb fileLicenseDb);

    /**
     * 
     * @param name
     * @return
     *     returns cacher.RuijieTb.QueryLicenseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryLicense", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.QueryLicense")
    @ResponseWrapper(localName = "queryLicenseResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.QueryLicenseResponse")
    public QueryLicenseResult queryLicense(
            @WebParam(name = "name", targetNamespace = "")
                    String name);

    /**
     * 
     * @param fileLicenseDb
     * @return
     *     returns cacher.RuijieTb.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delLicense", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.DelLicense")
    @ResponseWrapper(localName = "delLicenseResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.DelLicenseResponse")
    public SamApiBaseResult delLicense(
            @WebParam(name = "fileLicenseDb", targetNamespace = "")
                    FileLicenseDb fileLicenseDb);

    /**
     * 
     * @param password
     * @param txid
     * @param userId
     * @param cardNo
     * @param chargeCardType
     * @return
     *     returns cacher.RuijieTb.AccountOperationResult
     */
    @WebMethod(operationName = "ChargeCard")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ChargeCard", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.ChargeCard")
    @ResponseWrapper(localName = "ChargeCardResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.ChargeCardResponse")
    public AccountOperationResult chargeCard(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "chargeCardType", targetNamespace = "")
                    String chargeCardType,
            @WebParam(name = "cardNo", targetNamespace = "")
                    String cardNo,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "txid", targetNamespace = "")
                    String txid);

    /**
     * 
     * @param fee
     * @param txid
     * @param userId
     * @return
     *     returns cacher.RuijieTb.AccountOperationResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "preAccountFeeTransfer", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.PreAccountFeeTransfer")
    @ResponseWrapper(localName = "preAccountFeeTransferResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.PreAccountFeeTransferResponse")
    public AccountOperationResult preAccountFeeTransfer(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "fee", targetNamespace = "")
                    BigDecimal fee,
            @WebParam(name = "txid", targetNamespace = "")
                    String txid);

    /**
     * 
     * @param txid
     * @return
     *     returns cacher.RuijieTb.QueryTxidResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findExistTxCommand", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.FindExistTxCommand")
    @ResponseWrapper(localName = "findExistTxCommandResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.FindExistTxCommandResponse")
    public QueryTxidResult findExistTxCommand(
            @WebParam(name = "txid", targetNamespace = "")
                    String txid);

    /**
     * 
     * @param type
     * @param userId
     * @param value
     * @return
     *     returns cacher.RuijieTb.CompensatePeriodBillResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "compensatePeriodBill", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.CompensatePeriodBill")
    @ResponseWrapper(localName = "compensatePeriodBillResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.CompensatePeriodBillResponse")
    public CompensatePeriodBillResult compensatePeriodBill(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "type", targetNamespace = "")
                    int type,
            @WebParam(name = "value", targetNamespace = "")
                    BigDecimal value);

    /**
     * 
     * @param password
     * @param userId
     * @return
     *     returns cacher.RuijieTb.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verifyPassword", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.VerifyPassword")
    @ResponseWrapper(localName = "verifyPasswordResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.VerifyPasswordResponse")
    public SamApiBaseResult verifyPassword(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "password", targetNamespace = "")
                    String password);

    /**
     * 
     * @param password
     * @param userId
     * @return
     *     returns cacher.RuijieTb.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verifyAuthenResult", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.VerifyAuthenResult")
    @ResponseWrapper(localName = "verifyAuthenResultResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.VerifyAuthenResultResponse")
    public SamApiBaseResult verifyAuthenResult(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "password", targetNamespace = "")
                    String password);

    /**
     * 
     * @param userId
     * @return
     *     returns cacher.RuijieTb.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "suspendUser", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.SuspendUser")
    @ResponseWrapper(localName = "suspendUserResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.SuspendUserResponse")
    public SamApiBaseResult suspendUser(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId);

    /**
     * 
     * @param params
     * @return
     *     returns cacher.RuijieTb.QueryNtdFlowResult
     */
    @WebMethod
    @WebResult(name = "queryNtdFlowResult", targetNamespace = "")
    @RequestWrapper(localName = "queryNtdFlow", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.QueryNtdFlow")
    @ResponseWrapper(localName = "queryNtdFlowResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.QueryNtdFlowResponse")
    public QueryNtdFlowResult queryNtdFlow(
            @WebParam(name = "params", targetNamespace = "")
                    QueryNtdFlowParams params);

    /**
     * 
     * @param userId
     * @return
     *     returns cacher.RuijieTb.QueryUserPolicyInfoChangeResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryUserPolicyInfoChange", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.QueryUserPolicyInfoChange")
    @ResponseWrapper(localName = "queryUserPolicyInfoChangeResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.QueryUserPolicyInfoChangeResponse")
    public QueryUserPolicyInfoChangeResult queryUserPolicyInfoChange(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId);

    /**
     * 
     * @param password
     * @param userId
     * @return
     *     returns cacher.RuijieTb.VerifyLoginByAccountTypeResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verifyLoginByAccountType", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.VerifyLoginByAccountType")
    @ResponseWrapper(localName = "verifyLoginByAccountTypeResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.VerifyLoginByAccountTypeResponse")
    public VerifyLoginByAccountTypeResult verifyLoginByAccountType(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "password", targetNamespace = "")
                    String password);

    /**
     * 
     * @param operatorUserId
     * @param operatorUserPassword
     * @param userId
     * @param operatorName
     * @return
     *     returns cacher.RuijieTb.BindOperatorForSelfResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bindOperatorForSelf", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.BindOperatorForSelf")
    @ResponseWrapper(localName = "bindOperatorForSelfResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.BindOperatorForSelfResponse")
    public BindOperatorForSelfResult bindOperatorForSelf(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "operatorName", targetNamespace = "")
                    String operatorName,
            @WebParam(name = "operatorUserId", targetNamespace = "")
                    String operatorUserId,
            @WebParam(name = "operatorUserPassword", targetNamespace = "")
                    String operatorUserPassword);

    /**
     * 
     * @param compusName
     * @return
     *     returns cacher.RuijieTb.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "noticeReceiveFileFromCampus", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.NoticeReceiveFileFromCampus")
    @ResponseWrapper(localName = "noticeReceiveFileFromCampusResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.NoticeReceiveFileFromCampusResponse")
    public SamApiBaseResult noticeReceiveFileFromCampus(
            @WebParam(name = "compusName", targetNamespace = "")
                    String compusName);

    /**
     * 
     * @param jsonParam
     * @return
     *     returns cacher.RuijieTb.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "compensationPeriodic", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.CompensationPeriodic")
    @ResponseWrapper(localName = "compensationPeriodicResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.CompensationPeriodicResponse")
    public SamApiBaseResult compensationPeriodic(
            @WebParam(name = "jsonParam", targetNamespace = "")
                    String jsonParam);

    /**
     * 
     * @param compusName
     * @param port
     * @param actType
     * @return
     *     returns cacher.RuijieTb.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "noticeReceiveFile", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.NoticeReceiveFile")
    @ResponseWrapper(localName = "noticeReceiveFileResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.NoticeReceiveFileResponse")
    public SamApiBaseResult noticeReceiveFile(
            @WebParam(name = "compusName", targetNamespace = "")
                    String compusName,
            @WebParam(name = "actType", targetNamespace = "")
                    String actType,
            @WebParam(name = "port", targetNamespace = "")
                    int port);

    /**
     * 
     * @param blackListMessage
     * @param blackListFlag
     * @param userId
     * @param blackListExpireTime
     * @return
     *     returns cacher.RuijieTb.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "kickOnlineUser", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.KickOnlineUser")
    @ResponseWrapper(localName = "kickOnlineUserResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.KickOnlineUserResponse")
    public SamApiBaseResult kickOnlineUser(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "blackListFlag", targetNamespace = "")
                    int blackListFlag,
            @WebParam(name = "blackListExpireTime", targetNamespace = "")
                    int blackListExpireTime,
            @WebParam(name = "blackListMessage", targetNamespace = "")
                    String blackListMessage);

    /**
     * 
     * @return
     *     returns cacher.RuijieTb.FindSelfServPermResult
     */
    @WebMethod
    @WebResult(name = "findSelfServPermResult", targetNamespace = "")
    @RequestWrapper(localName = "findSelfServPerm", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.FindSelfServPerm")
    @ResponseWrapper(localName = "findSelfServPermResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.FindSelfServPermResponse")
    public FindSelfServPermResult findSelfServPerm();

    /**
     * 
     * @param params
     * @return
     *     returns cacher.RuijieTb.QueryAccountFlowResult
     */
    @WebMethod
    @WebResult(name = "queryAccountFlowResult", targetNamespace = "")
    @RequestWrapper(localName = "queryAccountFlow", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.QueryAccountFlow")
    @ResponseWrapper(localName = "queryAccountFlowResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.QueryAccountFlowResponse")
    public QueryAccountFlowResult queryAccountFlow(
            @WebParam(name = "params", targetNamespace = "")
                    QueryAccountFlowParams params);

    /**
     * 
     * @param params
     * @return
     *     returns cacher.RuijieTb.QueryUsedFreeFlowResult
     */
    @WebMethod
    @WebResult(name = "queryUsedFreeFlowResult", targetNamespace = "")
    @RequestWrapper(localName = "queryUsedFreeFlow", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.QueryUsedFreeFlow")
    @ResponseWrapper(localName = "queryUsedFreeFlowResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.QueryUsedFreeFlowResponse")
    public QueryUsedFreeFlowResult queryUsedFreeFlow(
            @WebParam(name = "params", targetNamespace = "")
                    QueryUsedFreeFlowParams params);

    /**
     * 
     * @param params
     * @return
     *     returns cacher.RuijieTb.QueryAccountFlowResult
     */
    @WebMethod
    @WebResult(name = "queryAccountFlowResult", targetNamespace = "")
    @RequestWrapper(localName = "queryAccountFlowAll", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.QueryAccountFlowAll")
    @ResponseWrapper(localName = "queryAccountFlowAllResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.QueryAccountFlowAllResponse")
    public QueryAccountFlowResult queryAccountFlowAll(
            @WebParam(name = "params", targetNamespace = "")
                    QueryAccountFlowAllParams params);

    /**
     * 
     * @param operatorUserId
     * @param operatorUserPassword
     * @param userId
     * @param operatorName
     * @return
     *     returns cacher.RuijieTb.BindOperatorForSelfResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bindOperatorV2", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.BindOperatorV2")
    @ResponseWrapper(localName = "bindOperatorV2Response", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.BindOperatorV2Response")
    public BindOperatorForSelfResult bindOperatorV2(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "operatorName", targetNamespace = "")
                    String operatorName,
            @WebParam(name = "operatorUserId", targetNamespace = "")
                    String operatorUserId,
            @WebParam(name = "operatorUserPassword", targetNamespace = "")
                    String operatorUserPassword);

    /**
     * 
     * @param operatorUserId
     * @param operatorUserPassword
     * @param userId
     * @param operatorName
     * @return
     *     returns cacher.RuijieTb.ReBindOperatorForSelfResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rebindOperatorV2", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.RebindOperatorV2")
    @ResponseWrapper(localName = "rebindOperatorV2Response", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.RebindOperatorV2Response")
    public ReBindOperatorForSelfResult rebindOperatorV2(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "operatorName", targetNamespace = "")
                    String operatorName,
            @WebParam(name = "operatorUserId", targetNamespace = "")
                    String operatorUserId,
            @WebParam(name = "operatorUserPassword", targetNamespace = "")
                    String operatorUserPassword);

    /**
     * 
     * @param userId
     * @return
     *     returns cacher.RuijieTb.FindPeriodicPaymentAmountForSelfResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findPeriodicPaymentAmountByUserId", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.FindPeriodicPaymentAmountByUserId")
    @ResponseWrapper(localName = "findPeriodicPaymentAmountByUserIdResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.FindPeriodicPaymentAmountByUserIdResponse")
    public FindPeriodicPaymentAmountForSelfResult findPeriodicPaymentAmountByUserId(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId);

    /**
     * 
     * @param params
     * @return
     *     returns cacher.RuijieTb.QueryBankAccountFlowResult
     */
    @WebMethod
    @WebResult(name = "queryBankAccountFlowResult", targetNamespace = "")
    @RequestWrapper(localName = "queryBankAccountFlow", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.QueryBankAccountFlow")
    @ResponseWrapper(localName = "queryBankAccountFlowResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.QueryBankAccountFlowResponse")
    public QueryBankAccountFlowResult queryBankAccountFlow(
            @WebParam(name = "params", targetNamespace = "")
                    QueryBankAccountFlowParams params);

    /**
     * 
     * @param userId
     * @return
     *     returns cacher.RuijieTb.VerifyPeriodStrategyUserResult
     */
    @WebMethod
    @WebResult(name = "verifyPeriodStrategyUserResult", targetNamespace = "")
    @RequestWrapper(localName = "verifyPeriodStrategyUser", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.VerifyPeriodStrategyUser")
    @ResponseWrapper(localName = "verifyPeriodStrategyUserResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.VerifyPeriodStrategyUserResponse")
    public VerifyPeriodStrategyUserResult verifyPeriodStrategyUser(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId);

    /**
     * 
     * @param templateName
     * @param operationTimeType
     * @param userPackageName
     * @param userId
     * @return
     *     returns cacher.RuijieTb.ModifyPackageConfirmInfosResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modifyPackageConfirmInfos", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.ModifyPackageConfirmInfos")
    @ResponseWrapper(localName = "modifyPackageConfirmInfosResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.ModifyPackageConfirmInfosResponse")
    public ModifyPackageConfirmInfosResult modifyPackageConfirmInfos(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "templateName", targetNamespace = "")
                    String templateName,
            @WebParam(name = "userPackageName", targetNamespace = "")
                    String userPackageName,
            @WebParam(name = "operationTimeType", targetNamespace = "")
                    short operationTimeType);

    /**
     * 
     * @param params
     * @return
     *     returns cacher.RuijieTb.QueryUserResult
     */
    @WebMethod
    @WebResult(name = "queryUserResult", targetNamespace = "")
    @RequestWrapper(localName = "queryUser", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.QueryUser")
    @ResponseWrapper(localName = "queryUserResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.QueryUserResponse")
    public QueryUserResult queryUser(
            @WebParam(name = "params", targetNamespace = "")
                    QueryUserParams params);

    /**
     * 
     * @param userTemplateName
     * @param operationTimeType
     * @param userPackageName
     * @param userId
     * @return
     *     returns cacher.RuijieTb.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modifyUserPackage", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.ModifyUserPackage")
    @ResponseWrapper(localName = "modifyUserPackageResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.ModifyUserPackageResponse")
    public SamApiBaseResult modifyUserPackage(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "userTemplateName", targetNamespace = "")
                    String userTemplateName,
            @WebParam(name = "userPackageName", targetNamespace = "")
                    String userPackageName,
            @WebParam(name = "operationTimeType", targetNamespace = "")
                    int operationTimeType);

    /**
     * 
     * @param userId
     * @return
     *     returns cacher.RuijieTb.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "logicDelUser", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.LogicDelUser")
    @ResponseWrapper(localName = "logicDelUserResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.LogicDelUserResponse")
    public SamApiBaseResult logicDelUser(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId);

    /**
     * 
     * @param password
     * @param userId
     * @return
     *     returns cacher.RuijieTb.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modifyPassword", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.ModifyPassword")
    @ResponseWrapper(localName = "modifyPasswordResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.ModifyPasswordResponse")
    public SamApiBaseResult modifyPassword(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "password", targetNamespace = "")
                    String password);

    /**
     * 
     * @param userId
     * @return
     *     returns cacher.RuijieTb.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "unbindOperatorForSelf", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.UnbindOperatorForSelf")
    @ResponseWrapper(localName = "unbindOperatorForSelfResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.UnbindOperatorForSelfResponse")
    public SamApiBaseResult unbindOperatorForSelf(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId);

    /**
     * 
     * @param operatorName
     * @param userId
     * @return
     *     returns cacher.RuijieTb.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "userSelfReset", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.UserSelfReset")
    @ResponseWrapper(localName = "userSelfResetResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.UserSelfResetResponse")
    public SamApiBaseResult userSelfReset(
            @WebParam(name = "operatorName", targetNamespace = "")
                    String operatorName,
            @WebParam(name = "userId", targetNamespace = "")
                    String userId);

    /**
     * 
     * @param password
     * @param txid
     * @param userId
     * @param cardNo
     * @param chargeCardType
     * @return
     *     returns cacher.RuijieTb.AccountOperationResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "chargeCardForSelf", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.ChargeCardForSelf")
    @ResponseWrapper(localName = "chargeCardForSelfResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.ChargeCardForSelfResponse")
    public AccountOperationResult chargeCardForSelf(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "chargeCardType", targetNamespace = "")
                    String chargeCardType,
            @WebParam(name = "cardNo", targetNamespace = "")
                    String cardNo,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "txid", targetNamespace = "")
                    String txid);

    /**
     * 
     * @param params
     * @return
     *     returns cacher.RuijieTb.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addUser", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.AddUser")
    @ResponseWrapper(localName = "addUserResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.AddUserResponse")
    public SamApiBaseResult addUser(
            @WebParam(name = "params", targetNamespace = "")
                    AddUserParams params);

    /**
     * 
     * @param params
     * @return
     *     returns cacher.RuijieTb.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addUserAndBindOperatorUserInfo", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.AddUserAndBindOperatorUserInfo")
    @ResponseWrapper(localName = "addUserAndBindOperatorUserInfoResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.AddUserAndBindOperatorUserInfoResponse")
    public SamApiBaseResult addUserAndBindOperatorUserInfo(
            @WebParam(name = "params", targetNamespace = "")
                    AddUserAndBindOperatorUserInfoParams params);

    /**
     * 
     * @param params
     * @return
     *     returns cacher.RuijieTb.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addUserAndBindOperatorNew", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.AddUserAndBindOperatorNew")
    @ResponseWrapper(localName = "addUserAndBindOperatorNewResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.AddUserAndBindOperatorNewResponse")
    public SamApiBaseResult addUserAndBindOperatorNew(
            @WebParam(name = "params", targetNamespace = "")
                    AddUserAndBindOperatorNewParams params);

    /**
     * 
     * @param params
     * @return
     *     returns cacher.RuijieTb.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addOrUpDateUserInfo", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.AddOrUpDateUserInfo")
    @ResponseWrapper(localName = "addOrUpDateUserInfoResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.AddOrUpDateUserInfoResponse")
    public SamApiBaseResult addOrUpDateUserInfo(
            @WebParam(name = "params", targetNamespace = "")
                    AddOrUpDateUserInfoParams params);

    /**
     * 
     * @param groupId
     * @param userId
     * @return
     *     returns cacher.RuijieTb.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modifyUserGroup", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.ModifyUserGroup")
    @ResponseWrapper(localName = "modifyUserGroupResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.ModifyUserGroupResponse")
    public SamApiBaseResult modifyUserGroup(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "groupId", targetNamespace = "")
                    String groupId);

    /**
     * 
     * @param params
     * @return
     *     returns cacher.RuijieTb.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "regUser", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.RegUser")
    @ResponseWrapper(localName = "regUserResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.RegUserResponse")
    public SamApiBaseResult regUser(
            @WebParam(name = "params", targetNamespace = "")
                    RegUserParams params);

    /**
     * 
     * @param params
     * @return
     *     returns cacher.RuijieTb.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modifyUser", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.ModifyUser")
    @ResponseWrapper(localName = "modifyUserResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.ModifyUserResponse")
    public SamApiBaseResult modifyUser(
            @WebParam(name = "params", targetNamespace = "")
                    ModifyUserParams params);

    /**
     * 
     * @param userId
     * @return
     *     returns cacher.RuijieTb.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delUser", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.DelUser")
    @ResponseWrapper(localName = "delUserResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.DelUserResponse")
    public SamApiBaseResult delUser(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId);

    /**
     * 
     * @return
     *     returns cacher.RuijieTb.QueryAllCustomFieldResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAllCustomFieldForUserinfo", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.FindAllCustomFieldForUserinfo")
    @ResponseWrapper(localName = "findAllCustomFieldForUserinfoResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.FindAllCustomFieldForUserinfoResponse")
    public QueryAllCustomFieldResult findAllCustomFieldForUserinfo();

    /**
     * 
     * @param messageType
     * @param message
     * @param userId
     * @return
     *     returns cacher.RuijieTb.SendMessageResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendMessage", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.SendMessage")
    @ResponseWrapper(localName = "sendMessageResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.SendMessageResponse")
    public SendMessageResult sendMessage(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "message", targetNamespace = "")
                    String message,
            @WebParam(name = "messageType", targetNamespace = "")
                    int messageType);

    /**
     * 
     * @param password
     * @param userId
     * @return
     *     returns cacher.RuijieTb.VerifyManagerPasswordResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verifyManagerPassword", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.VerifyManagerPassword")
    @ResponseWrapper(localName = "verifyManagerPasswordResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.VerifyManagerPasswordResponse")
    public VerifyManagerPasswordResult verifyManagerPassword(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "password", targetNamespace = "")
                    String password);

    /**
     * 
     * @param operatorUserId
     * @param operatorUserPassword
     * @param userId
     * @param operatorName
     * @return
     *     returns cacher.RuijieTb.ReBindOperatorForSelfResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rebindOperatorForSlef", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.RebindOperatorForSlef")
    @ResponseWrapper(localName = "rebindOperatorForSlefResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.RebindOperatorForSlefResponse")
    public ReBindOperatorForSelfResult rebindOperatorForSlef(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "operatorName", targetNamespace = "")
                    String operatorName,
            @WebParam(name = "operatorUserId", targetNamespace = "")
                    String operatorUserId,
            @WebParam(name = "operatorUserPassword", targetNamespace = "")
                    String operatorUserPassword);

    /**
     * 
     * @param userId
     * @return
     *     returns cacher.RuijieTb.QueryPermissionListForPhoneSelfResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryPermissionListForPhoneSelf", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.QueryPermissionListForPhoneSelf")
    @ResponseWrapper(localName = "queryPermissionListForPhoneSelfResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.QueryPermissionListForPhoneSelfResponse")
    public QueryPermissionListForPhoneSelfResult queryPermissionListForPhoneSelf(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId);

    /**
     * 
     * @param params
     * @return
     *     returns cacher.RuijieTb.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateUserBindInfo", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.UpdateUserBindInfo")
    @ResponseWrapper(localName = "updateBindInfoResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.UpdateBindInfoResponse")
    public SamApiBaseResult updateUserBindInfo(
            @WebParam(name = "params", targetNamespace = "")
                    SpiUserBindInfo params);

    /**
     * 
     * @param params
     * @return
     *     returns cacher.RuijieTb.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateUserBindInfoV2", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.UpdateUserBindInfoV2")
    @ResponseWrapper(localName = "updateBindInfoV2Response", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.UpdateBindInfoV2Response")
    public SamApiBaseResult updateUserBindInfoV2(
            @WebParam(name = "params", targetNamespace = "")
                    SpiUserBindInfoV2 params);

    /**
     * 
     * @param userId
     * @return
     *     returns cacher.RuijieTb.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "reLogicDelUser", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.ReLogicDelUser")
    @ResponseWrapper(localName = "reLogicDelUserResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.ReLogicDelUserResponse")
    public SamApiBaseResult reLogicDelUser(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId);

    /**
     * 
     * @param param
     * @return
     *     returns cacher.RuijieTb.QueryOnlineUserResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryOnlineUser", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.QueryOnlineUser")
    @ResponseWrapper(localName = "queryOnlineUserResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.QueryOnlineUserResponse")
    public QueryOnlineUserResult queryOnlineUser(
            @WebParam(name = "param", targetNamespace = "")
                    QueryOnlineUserParam param);

    /**
     * 
     * @param param
     * @return
     *     returns cacher.RuijieTb.QueryOnlineUserResultV2
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryOnlineUserV2", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.QueryOnlineUserV2")
    @ResponseWrapper(localName = "queryOnlineUserResponseV2", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.QueryOnlineUserResponseV2")
    public QueryOnlineUserResultV2 queryOnlineUserV2(
            @WebParam(name = "param", targetNamespace = "")
                    QueryOnlineUserParam param);

    /**
     * 
     * @return
     *     returns cacher.RuijieTb.FindOnlineUserCountResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findOnlineUserCount", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.FindOnlineUserCount")
    @ResponseWrapper(localName = "findOnlineUserCountResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.FindOnlineUserCountResponse")
    public FindOnlineUserCountResult findOnlineUserCount();

    /**
     * 
     * @param spiUserBindInfo
     * @param userId
     * @return
     *     returns cacher.RuijieTb.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addUserBindInfo", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.AddUserBindInfo")
    @ResponseWrapper(localName = "addUserBindInfoResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.AddUserBindInfoResponse")
    public SamApiBaseResult addUserBindInfo(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "spiUserBindInfo", targetNamespace = "")
                    SpiUserBindInfo spiUserBindInfo);

    /**
     * 
     * @param spiUserBindInfoV2
     * @param userId
     * @return
     *     returns cacher.RuijieTb.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addUserBindInfoV2", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.AddUserBindInfoV2")
    @ResponseWrapper(localName = "addUserBindInfoResponseV2", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.AddUserBindInfoResponseV2")
    public SamApiBaseResult addUserBindInfoV2(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "spiUserBindInfoV2", targetNamespace = "")
                    SpiUserBindInfoV2 spiUserBindInfoV2);

    /**
     * 
     * @param userBindInfoUuid
     * @return
     *     returns cacher.RuijieTb.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteUserBindInfo", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.DeleteUserBindInfo")
    @ResponseWrapper(localName = "deleteUserBindInfoResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.DeleteUserBindInfoResponse")
    public SamApiBaseResult deleteUserBindInfo(
            @WebParam(name = "userBindInfoUuid", targetNamespace = "")
                    String userBindInfoUuid);

    /**
     * 
     * @return
     *     returns cacher.RuijieTb.FindAllUserGroupsResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAllUserGroups", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.FindAllUserGroups")
    @ResponseWrapper(localName = "findAllUserGroupsResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.FindAllUserGroupsResponse")
    public FindAllUserGroupsResult findAllUserGroups();

    /**
     * 
     * @param userId
     * @return
     *     returns cacher.RuijieTb.FindUserBindInfoByUserIdResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findUserBindInfoByUserId", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.FindUserBindInfoByUserId")
    @ResponseWrapper(localName = "findUserBindInfoByUserIdResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.FindUserBindInfoByUserIdResponse")
    public FindUserBindInfoByUserIdResult findUserBindInfoByUserId(
            @WebParam(name = "UserId", targetNamespace = "")
                    String userId);

    /**
     * 
     * @param userId
     * @return
     *     returns cacher.RuijieTb.FindUserBindInfoByUserIdResultV2
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findUserBindInfoByUserIdV2", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.FindUserBindInfoByUserIdV2")
    @ResponseWrapper(localName = "findUserBindInfoByUserIdResponseV2", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.FindUserBindInfoByUserIdResponseV2")
    public FindUserBindInfoByUserIdResultV2 findUserBindInfoByUserIdV2(
            @WebParam(name = "UserId", targetNamespace = "")
                    String userId);

    /**
     * 
     * @return
     *     returns cacher.RuijieTb.FindAllUserTemplatePackagesResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAllUserTemplatePackages", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.FindAllUserTemplatePackages")
    @ResponseWrapper(localName = "findAllUserTemplatePackagesResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.FindAllUserTemplatePackagesResponse")
    public FindAllUserTemplatePackagesResult findAllUserTemplatePackages();

    /**
     * 
     * @param changeType
     * @param packageId
     * @param userId
     * @return
     *     returns cacher.RuijieTb.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "changePackage4Self", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.ChangePackage4Self")
    @ResponseWrapper(localName = "changePackage4SelfResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.ChangePackage4SelfResponse")
    public SamApiBaseResult changePackage4Self(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "packageId", targetNamespace = "")
                    String packageId,
            @WebParam(name = "changeType", targetNamespace = "")
                    String changeType);

    /**
     * 
     * @param userId
     * @return
     *     returns cacher.RuijieTb.FindManagerInfoByIdResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findManagerInfoById", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.FindManagerInfoById")
    @ResponseWrapper(localName = "findManagerInfoByIdResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.FindManagerInfoByIdResponse")
    public FindManagerInfoByIdResult findManagerInfoById(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId);

    /**
     * 
     * @param noticeContent
     * @param deviceIps
     * @param noticeExpireTtime
     * @return
     *     returns cacher.RuijieTb.SendMessageByDeviceResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendMessageByDevice", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.SendMessageByDevice")
    @ResponseWrapper(localName = "sendMessageByDeviceResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.SendMessageByDeviceResponse")
    public SendMessageByDeviceResult sendMessageByDevice(
            @WebParam(name = "deviceIps", targetNamespace = "")
                    List<String> deviceIps,
            @WebParam(name = "noticeContent", targetNamespace = "")
                    String noticeContent,
            @WebParam(name = "noticeExpireTtime", targetNamespace = "")
                    XMLGregorianCalendar noticeExpireTtime);

    /**
     * 
     * @param params
     * @return
     *     returns cacher.RuijieTb.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addInhibit", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.AddInhibit")
    @ResponseWrapper(localName = "addInhibitResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.AddInhibitResponse")
    public SamApiBaseResult addInhibit(
            @WebParam(name = "params", targetNamespace = "")
                    AddInhibitParams params);

    /**
     * 
     * @param params
     * @return
     *     returns cacher.RuijieTb.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addInhibitV2", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.AddInhibitV2")
    @ResponseWrapper(localName = "addInhibitResponseV2", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.AddInhibitResponseV2")
    public SamApiBaseResult addInhibitV2(
            @WebParam(name = "params", targetNamespace = "")
                    AddInhibitParamsV2 params);

    /**
     * 
     * @param param
     * @return
     *     returns cacher.RuijieTb.QueryInhibitResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryInhibit", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.QueryInhibit")
    @ResponseWrapper(localName = "queryInhibitResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.QueryInhibitResponse")
    public QueryInhibitResult queryInhibit(
            @WebParam(name = "param", targetNamespace = "")
                    QueryInhibitParam param);

    /**
     * 
     * @param param
     * @return
     *     returns cacher.RuijieTb.QueryInhibitResultV2
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryInhibitV2", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.QueryInhibitV2")
    @ResponseWrapper(localName = "queryInhibitResponseV2", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.QueryInhibitResponseV2")
    public QueryInhibitResultV2 queryInhibitV2(
            @WebParam(name = "param", targetNamespace = "")
                    QueryInhibitParamV2 param);

    /**
     * 
     * @param uuid
     * @return
     *     returns cacher.RuijieTb.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteInhibit", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.DeleteInhibit")
    @ResponseWrapper(localName = "deleteInhibitResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.DeleteInhibitResponse")
    public SamApiBaseResult deleteInhibit(
            @WebParam(name = "uuid", targetNamespace = "")
                    String uuid);

    /**
     * 
     * @param userId
     * @return
     *     returns cacher.RuijieTb.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "unbindOperator", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.UnbindOperator")
    @ResponseWrapper(localName = "unbindOperatorResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.UnbindOperatorResponse")
    public SamApiBaseResult unbindOperator(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId);

    /**
     * 
     * @param compusName
     * @param operatorId
     * @return
     *     returns cacher.RuijieTb.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "unbindOperatorOfCompus", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.UnbindOperatorOfCompus")
    @ResponseWrapper(localName = "unbindOperatorOfCompusResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.UnbindOperatorOfCompusResponse")
    public SamApiBaseResult unbindOperatorOfCompus(
            @WebParam(name = "operatorId", targetNamespace = "")
                    String operatorId,
            @WebParam(name = "compusName", targetNamespace = "")
                    String compusName);

    /**
     * 
     * @param atName
     * @param enableType
     * @param packageId
     * @param userId
     * @return
     *     returns cacher.RuijieTb.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modifyUserPackageForSelf", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.ModifyUserPackageForSelf")
    @ResponseWrapper(localName = "modifyUserPackageForSelfResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.ModifyUserPackageForSelfResponse")
    public SamApiBaseResult modifyUserPackageForSelf(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "atName", targetNamespace = "")
                    String atName,
            @WebParam(name = "packageId", targetNamespace = "")
                    String packageId,
            @WebParam(name = "enableType", targetNamespace = "")
                    int enableType);

    /**
     * 
     * @param operatorUserId
     * @param operatorUserPassword
     * @param userId
     * @param operatorName
     * @return
     *     returns cacher.RuijieTb.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rebindOperator", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.RebindOperator")
    @ResponseWrapper(localName = "rebindOperatorResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.RebindOperatorResponse")
    public SamApiBaseResult rebindOperator(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "operatorName", targetNamespace = "")
                    String operatorName,
            @WebParam(name = "operatorUserId", targetNamespace = "")
                    String operatorUserId,
            @WebParam(name = "operatorUserPassword", targetNamespace = "")
                    String operatorUserPassword);

    /**
     * 
     * @param newOperatorUserId
     * @param compusName
     * @param newOperatorUserPassword
     * @param oldOperatorUserId
     * @return
     *     returns cacher.RuijieTb.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rebindOperatorOfCompus", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.RebindOperatorOfCompus")
    @ResponseWrapper(localName = "rebindOperatorOfCompusResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.RebindOperatorOfCompusResponse")
    public SamApiBaseResult rebindOperatorOfCompus(
            @WebParam(name = "oldOperatorUserId", targetNamespace = "")
                    String oldOperatorUserId,
            @WebParam(name = "compusName", targetNamespace = "")
                    String compusName,
            @WebParam(name = "newOperatorUserId", targetNamespace = "")
                    String newOperatorUserId,
            @WebParam(name = "newOperatorUserPassword", targetNamespace = "")
                    String newOperatorUserPassword);

    /**
     * 
     * @param operatorUserId
     * @param operatorUserPassword
     * @param userId
     * @param operatorName
     * @return
     *     returns cacher.RuijieTb.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bindOperator", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.BindOperator")
    @ResponseWrapper(localName = "bindOperatorResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.BindOperatorResponse")
    public SamApiBaseResult bindOperator(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "operatorName", targetNamespace = "")
                    String operatorName,
            @WebParam(name = "operatorUserId", targetNamespace = "")
                    String operatorUserId,
            @WebParam(name = "operatorUserPassword", targetNamespace = "")
                    String operatorUserPassword);

    /**
     * 
     * @param operatorUserId
     * @param operatorUserPassword
     * @param operatorIp
     * @param actType
     * @param userId
     * @return
     *     returns cacher.RuijieTb.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "operatorHandle", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.OperatorHandle")
    @ResponseWrapper(localName = "operatorHandleResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.OperatorHandleResponse")
    public SamApiBaseResult operatorHandle(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "operatorIp", targetNamespace = "")
                    String operatorIp,
            @WebParam(name = "operatorUserId", targetNamespace = "")
                    String operatorUserId,
            @WebParam(name = "operatorUserPassword", targetNamespace = "")
                    String operatorUserPassword,
            @WebParam(name = "actType", targetNamespace = "")
                    String actType);

    /**
     * 
     * @param userId
     * @param operatorId
     * @param operatorName
     * @return
     *     returns cacher.RuijieTb.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "unbindOperatorByParam", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.UnbindOperatorByParam")
    @ResponseWrapper(localName = "unbindOperatorByParamResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.UnbindOperatorByParamResponse")
    public SamApiBaseResult unbindOperatorByParam(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "operatorId", targetNamespace = "")
                    String operatorId,
            @WebParam(name = "operatorName", targetNamespace = "")
                    String operatorName);

    /**
     * 
     * @param userId
     * @return
     *     returns cacher.RuijieTb.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "suspend4SelfPermission", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.Suspend4SelfPermission")
    @ResponseWrapper(localName = "suspend4SelfPermissionResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.Suspend4SelfPermissionResponse")
    public SamApiBaseResult suspend4SelfPermission(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId);

    /**
     * 
     * @param userId
     * @return
     *     returns cacher.RuijieTb.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "resume4SelfPermission", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.Resume4SelfPermission")
    @ResponseWrapper(localName = "resume4SelfPermissionResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.Resume4SelfPermissionResponse")
    public SamApiBaseResult resume4SelfPermission(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId);

    /**
     * 
     * @param messageType
     * @param message
     * @param userId
     * @return
     *     returns cacher.RuijieTb.SendMessageV2Result
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendMessageV2", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.SendMessageV2")
    @ResponseWrapper(localName = "sendMessageV2Response", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.SendMessageV2Response")
    public SendMessageV2Result sendMessageV2(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "message", targetNamespace = "")
                    String message,
            @WebParam(name = "messageType", targetNamespace = "")
                    int messageType);

    /**
     * 
     * @param userId
     * @return
     *     returns cacher.RuijieTb.FindFlowRefuelPackageListByUserIdResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findFlowRefuelPackageListByUserId", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.FindFlowRefuelPackageListByUserId")
    @ResponseWrapper(localName = "findFlowRefuelPackageListByUserIdResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.FindFlowRefuelPackageListByUserIdResponse")
    public FindFlowRefuelPackageListByUserIdResult findFlowRefuelPackageListByUserId(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId);

    /**
     * 
     * @param flowRefuelPackageUuid
     * @param userId
     * @return
     *     returns cacher.RuijieTb.PurchaseFlowRefuelPackageResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "purchaseFlowRefuelPackage", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.PurchaseFlowRefuelPackage")
    @ResponseWrapper(localName = "purchaseFlowRefuelPackageResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "cacher.RuijieTb.PurchaseFlowRefuelPackageResponse")
    public PurchaseFlowRefuelPackageResult purchaseFlowRefuelPackage(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "flowRefuelPackageUuid", targetNamespace = "")
                    String flowRefuelPackageUuid);

}
